export const PROJECTS = [
  {
    id: 'project1',
    name: 'Project 1',
    color: '#3cb44b',
    totalTime: 10 * 5 * 60,
    elapsedTime: 3 * 5 * 60,
    totalTask: 2,
    taskComplete: 0,
    ownerId: 'user1',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'project2',
    name: 'Project 2',
    color: '#93b0f3',
    totalTime: 4 * 5 * 60,
    elapsedTime: 0,
    totalTask: 4,
    taskComplete: 0,
    ownerId: 'user1',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'project3',
    name: 'Project 3',
    color: '#fff47c',
    totalTime: 4 * 5 * 60,
    elapsedTime: 2 * 5 * 60,
    totalTask: 6,
    taskComplete: 2,
    ownerId: 'user2',
    createdAt: new Date().toISOString(),
  },
];
