export const colors = {
  light: {
    primary: '#93b0f3',
    primaryDark: '#7393dd',
    primaryLight: '#bacfff',
    secondary: '#53d3af',
    text: '#000',
    texSec: '#adb5bd',
    background: '#fff',
    backgroundSec: '#f7f7fC',
    buttonSec: '#bacfff',
    buttonTextSec: '#93b0f3',
    border: '#f5f5f5',
    error: '#ff3f3f',
  },
  dark: {
    primary: '#93b0f3',
    primaryDark: '#7393dd',
    primaryLight: '#bacfff',
    secondary: '#ee5436',
    text: '#fff',
    texSec: '#adb5bd',
    background: '#181a20',
    backgroundSec: '#282c36',
    buttonSec: '#35383f',
    buttonTextSec: '#fff',
    border: '#262930',
    error: '#ff3f3f',
  },
};
